# App-specific tweaks
source = ~/.config/hypr/apps/discord.conf
source = ~/.config/hypr/apps/polychromatic.conf
source = ~/.config/hypr/apps/spotify.conf
source = ~/.config/hypr/apps/android-emulator.conf
source = ~/.config/hypr/apps/bitwarden.conf